# Uncomment the next line to define a global platform for your project

use_frameworks!

target 'stat' do

# Comment the next line if you're not using Swift and don't want to use dynamic frameworks

pod 'Firebase/Core'
pod 'Firebase/Database'
pod 'Firebase/Auth'
pod 'Firebase/Storage'
pod 'Alamofire', '~> 4.7'
pod 'Hero'
pod 'CircularSlider'
end
